- name: create direcrory /home/testuser/app/conf/
  ansible.builtin.file:
    - path: /home/testuser/app/conf/
    - state: directory
    - owner: testuser
    - group: testuser
    - mode: '0750'
    - recurse: yes


- name: create direcrory /home/testuser/app/bin/
  ansible.builtin.file:
    - path: /home/testuser/app/bin/
    - state: directory
    - owner: testuser
    - group: testuser
    - mode: '0750'
    - recurse: yes


- name: copy conf files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/testuser/app/conf/
    owner: testuser
    mode: '0750'
  with_items:
    - files/web.conf
    - files/app.conf

